name: Smoke test via yarn berry
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
            node-version: '16'
      - run: yarn install
      - run: yarn set version berry
      - name: run chromatic
        run: npx -p . chromatic --build-script-name build-test-storybook --exit-zero-on-changes --force-rebuild
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.SMOKE_TESTS_CHROMATIC_PROJECT_TOKEN }}
