name: Smoke test via Node 12
on: push

jobs:
  self-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: yarn
      - run: yarn build
      - uses: ./
        with:
          buildScriptName: build-test-storybook
          exitZeroOnChanges: true
          forceRebuild: true
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.SMOKE_TESTS_CHROMATIC_PROJECT_TOKEN }}
