name: Smoke test via yarn berry
on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: rm subdir/yarn.lock # remove conflicting lockfile
      - run: yarn set version berry
      - run: yarn install
      - name: run chromatic
        run: npx -p . chromatic --build-script-name build-test-storybook --exit-zero-on-changes --force-rebuild
        env:
          LOG_LEVEL: debug
          DEBUG: chromatic-cli
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.SMOKE_TESTS_CHROMATIC_PROJECT_TOKEN }}
